### ISSUE TITLE
typos & suggestions

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/tidyverse-lesson#2]
typos
- tranformation
- "opinonated collected of R"
- “term”” column of the

suggestions
- link to "prior lesson"
- include acs_cbp.csv in training data / handouts
- explain loss of records with augment on acs_cbp
- pipe within pipe is a bit much, no?
- start with `install.packages('tidyverse')`
- include map_df in the fs package documentation (probably not your job, but c'mon!)

**Comment by khondula** [comment]
Also:

* too long
* needs better purrr explanation, which probably would fit better if lesson is reordered to start with fs.

**Comment by reblake** [comment]
I second some of these comments and add some others:
- either make entirely stand-alone (preferred I think), or actually insert hyperlink to prior lesson.  Felt like I was dropped into the middle of something at the beginning.
- re-order the sections; make start with "File manipulation" section, including purrr and stringr
- introduce the "piped workflow" concept at the very beginning
- update to include vroom for reading in folders of files https://www.tidyverse.org/blog/2019/05/vroom-1-0-0/#reading-multiple-files
- return of `rowwise()` to dplyr  https://dplyr.tidyverse.org/articles/rowwise.html
